### ISSUE TITLE
what does this do

### ISSUE THREAD

**Issue by Cxsmo-ai** [GooseMod/defiant#2]
what does this do

**Comment by adntaha** [comment]
a very basic client mod for discord i think, also there's a support server

**Comment by CanadaHonk** [comment]
it's not that

**Comment by lexisother** [comment]
the above statement is correct

**Comment by maisymoe** [comment]
i agree with the statement above my own

**Comment by jamesbt365** [comment]
I also agree

**Comment by CanadaHonk** [comment]
defiant was a universal remapper for new webpack keys to old (restoring old props). no longer in development as too much work for little long-term payoff.
